xyz-modem: Select CRC16
CONFIG_LOADB causes the xyzModem code to get built and that code depends
on CONFIG_CRC16. If you don't have something else that selects CONFIG_CRC16
you can unselect it and then the final link will fail:

  LD      u-boot
/usr/bin/m68k-linux-gnu-ld.bfd: common/xyzModem.o: in function `xyzModem_get_hdr':
u-boot/common/xyzModem.c:388:(.text.xyzModem_get_hdr+0x17a): undefined reference to `crc16_ccitt'

Since SPL/TPL can also use the xyzModem code create a Kconfig symbol for
it, select CONFIG_CRC16 there and then select the new symbol from all of
the users.

Signed-off-by: Daniel Palmer <daniel@thingy.jp>